# Generated by Django 4.2.11 on 2024-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_producto_stock_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('procesadores', 'Procesadores'), ('placas_madre', 'Placas Madre'), ('memoria_ram', 'Memoria RAM'), ('tarjeta_grafica', 'Tarjeta Gráfica'), ('almacenamiento', 'Almacenamiento'), ('fuente_poder', 'Fuente de Poder'), ('gabinete', 'Gabinete'), ('monitor', 'Monitor')], default='procesadores', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
