# Generated by Django 4.2.11 on 2024-11-22 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_producto_categoria_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-created',), 'verbose_name_plural': 'productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR3', 'LPDDR3'), ('LPDDR4', 'LPDDR4'), ('LPDDR5', 'LPDDR5')], max_length=50, null=True),
        ),
        migrations.AddField(
        model_name='producto',
        name='price',
        field=models.DecimalField(decimal_places=2, default=0.00, max_digits=8),
        preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='socket_type',
            field=models.CharField(blank=True, choices=[('AM5', 'AM5'), ('AM4', 'AM4'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('TR4', 'TR4'), ('LGA1151', 'LGA1151'), ('BGA', 'BGA')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='title',
            field=models.CharField(default='Producto sin título', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='watts',
            field=models.PositiveIntegerField(blank=True, choices=[(10, '10W'), (20, '20W'), (30, '30W'), (50, '50W'), (100, '100W'), (200, '200W'), (300, '300W'), (400, '400W'), (500, '500W'), (600, '600W'), (700, '700W'), (800, '800W'), (1000, '1000W'), (1200, '1200W'), (1400, '1400W'), (1600, '1600W')], null=True),
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_with', models.ManyToManyField(related_name='productos_compatibles', to='web.producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='web.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='web.category'),
        ),
    ]
