# Generated by Django 4.2.11 on 2024-11-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('procesadores', 'Procesadores'), ('placas_madre', 'Placas Madre'), ('memoria_ram', 'Memoria RAM'), ('tarjeta_grafica', 'Tarjeta Gráfica'), ('almacenamiento', 'Almacenamiento'), ('fuente_poder', 'Fuente de Poder'), ('gabinete', 'Gabinete'), ('monitor', 'Monitor')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
