# Generated by Django 4.2.11 on 2024-11-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_category_descripcion_category_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
