# Generated by Django 4.2.11 on 2024-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
