# Generated by Django 4.2.11 on 2024-11-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_carrito_comprado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/'),
        ),
    ]
