# Generated by Django 4.2.11 on 2024-11-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('procesadores', 'Procesadores'), ('placas_madre', 'Placas Madre'), ('memoria_ram', 'Memoria RAM'), ('tarjeta_grafica', 'Tarjeta Gráfica'), ('almacenamiento', 'Almacenamiento'), ('fuente_poder', 'Fuente de Poder'), ('gabinete', 'Gabinete'), ('monitor', 'Monitor'), ('cooler', 'Cooler')], max_length=50),
        ),
    ]
