# Generated by Django 4.2.11 on 2024-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_producto_imagen_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
