# Generated by Django 4.2.11 on 2024-11-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
